pepfile: config/pep/config.yaml

sequencing: "ont" # "ont" or "illumina"
samtools_q_flag: 10
gene_loc: "/resources/gene_loci.csv"

mtb-genome-download-path:
  - ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/195/955/GCA_000195955.2_ASM19595v2/GCA_000195955.2_ASM19595v2_genomic.fna.gz

human-genome-download-path:
  - ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.28_GRCh38.p13/GCA_000001405.28_GRCh38.p13_genomic.fna.gz

illumina_adapters:
  - -a CTGTCTCTTATACACATCT -g AGATGTGTATAAGAGACAG

preprocessing:
  amplicon-reference: "AL123456"
  amplicon-ref-ver: "AL123456.3"

reduced-analysis: False